services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    ports:
      - '6543:5432'
    networks:
      - express_network

  redis:
    image: redis
    container_name: redis_container
    restart: always
    volumes: 
      - ./docker/redis:/data
    ports:
      - '6379:6379'
    networks:
      - express_network

  db_testing:
    image: postgres
    container_name: postgres_testing_container
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - '7654:5432'

networks:
  express_network:
